pipeline {
    agent any

    environment {
        // Local deployment için değişkenler
        ANSIBLE_TIMEOUT = '60'
        INVENTORY = 'localhost ansible_connection=local'
        PLAYBOOK = "${WORKSPACE}/ansible/playbook.yml"
    }

    options {
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Prepare Ansible') {
            steps {
                sh '''
                    mkdir -p ${WORKSPACE}/ansible
                    cat > ${WORKSPACE}/ansible/playbook.yml << 'EOL'
---
- hosts: all
  become: true
  
  tasks:
    - name: Test connection
      ping:
      
    - name: Update package cache
      dnf:
        update_cache: yes
EOL
                '''
            }
        }

        stage('Test Connection') {
            steps {
                sh "ansible -i '${INVENTORY},' all -m ping -vvv"
            }
        }
        
        stage('Deploy with Ansible') {
            steps {
                sh "ansible-playbook -i '${INVENTORY},' ${PLAYBOOK} -vvv"
            }
        }
    }

    post {
        success {
            echo 'Deployment başarılı!'
        }
        failure {
            echo 'Deployment başarısız!'
        }
        aborted {
            echo 'Pipeline iptal'
        }
    }
}