pipeline {
    agent any

    environment {
        // Timeout değeri eklendi
        ANSIBLE_TIMEOUT = '60' // seconds
        INVENTORY = '3.120.129.244,'
        PLAYBOOK = '/var/lib/jenkins/workspace/eco/ansible/playbook.yml'
    }

    options {
        // Pipeline timeout eklendi
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Test Connection') {
            steps {
                // Verbose mod ile bağlantı testi
                sh "ansible -i ${INVENTORY} all -m ping -vvv"
            }
        }
        
        stage('Deploy with Ansible') {
            steps {
                // Timeout ve verbose mod eklendi
                sh "ANSIBLE_TIMEOUT=${ANSIBLE_TIMEOUT} ansible-playbook -i ${INVENTORY} ${PLAYBOOK} -vvv"
            }
        }
    }

    post {
        success {
            echo 'Deployment başarılı!'
        }
        failure {
            echo 'Deployment başarısız!'
        }
        aborted {
            echo 'Pipeline iptal edildi!'
        }
    }
}