- name: Ensure common packages are installed
  apt:
    name:
      - git
      - curl
      - vim
    state: present

- name: Create a directory for application
  file:
    path: /opt/myapp
    state: directory

- name: Copy configuration file
  template:
    src: config.j2
    dest: /opt/myapp/config.yml

- name: Start application service
  systemd:
    name: myapp
    state: started
    enabled: yes